language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

addons:
    code_climate:
        repo_token: c5a0e7f547f9961f0dff9d813e2c42586eff701082e399e619868c0e4e2507f5

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    ./init --env=Development
    sed -i s/root/travis/ common/config/main-local.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" frontend/config/main.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php

before_script:
  - mysql -e 'CREATE DATABASE yii2advanced_test;'
  - php yii_test migrate --interactive=0
  - phantomjs --webdriver=4444 &
  - php -S 127.0.0.1:8080 -t 'frontend/web' > /dev/null 2>&1 &
  - sleep 5
  - touch common/config/config.yml

script:
  - composer validate --strict
  - vendor/bin/codecept run

after_success:
  - ls
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/test-reporter
